#!/bin/bash
set -e

echo
echo '#'
echo '# This System Report was generated by: https://github.com/donvigo/docker-android-cordova/blob/master/system_report.sh'
echo '#  Pull Requests are welcome!'
echo '#'
echo

echo
echo "=== Revision / ID ======================"
if [ -z "$BITRISE_DOCKER_REV_NUMBER_ANDROID_CORDOVA" ] ; then
  echo " [!] No BITRISE_DOCKER_REV_NUMBER_ANDROID_CORDOVA defined!"
  exit 1
fi
echo "* BITRISE_DOCKER_REV_NUMBER_ANDROID_CORDOVA: $BITRISE_DOCKER_REV_NUMBER_ANDROID_CORDOVA"
echo "========================================"
echo


# Make sure that the reported version is only
#  a single line!
echo
echo "=== Pre-installed tool versions ========"

ver_line="$(nodejs -v)" ;     echo "* NodeJS: $ver_line"
ver_line="$(npm -v)" ;        echo "* npm: $ver_line"
ver_line="$(cordova -v)" ;    echo "* Cordova: $ver_line"

echo "========================================"
echo

echo
echo "=== npm packages ======================="
npm list -g --depth=0
echo "========================================"
echo
